### ISSUE TITLE
how to use web-ui?

### ISSUE THREAD

**Issue by jonqiao** [casbin/web-ui#1]
I can not access the link in the example part....
how can I use this web-ui in my own node-casbin application?? 
should I develop the web part by myself ?? any guide there???

**Comment by hsluoyz** [comment]
Hi @jonqiao , the example website is down. This project is a Python 2.7 Django site. But the frontend (html, js, etc) can be shared. You can develop your own backend if you are using Node.js as backend.

We have plan to improve this project but slightly lack of developers. Let me know if you want to contribute :)

**Comment by hsluoyz** [comment]
Closed as stale.
