### ISSUE TITLE
Does this project have a running version and documentation ?

### ISSUE THREAD

**Issue by raduone** [casbin/web-ui#1]
I see in the Casbin documentation that this is the repository for the UI module. Is this a TO BE DONE feature ?

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/casbin-dashboard

**Comment by jgm-ktg** [comment]
What happened to PolicyEditor.html etc?  I looked at casbin-dashboard but it doesn't seem to have that functionality?

**Comment by hsluoyz** [comment]
We re-write the model and policy editor, see: https://dashboard.casbin.org/adapter/adapter_1
