### ISSUE TITLE
What is the purpose or intent of the web-ui?

### ISSUE THREAD

**Issue by chmorgan** [casbin/web-ui#3]
Is the web-ui project intended to plug into a database via an adapter to provide a policy interface or is it just an example of how someone might provide a ui for a Casbin data store?

If you can provide clarification here I can open a pull request against README.md to clarify.

**Comment by hsluoyz** [comment]
I want it to be the official web UI for Casbin, so people can view, add, remove policy rules for their enforcer. But currently it cannot fully serve that purpose yet..

**Comment by chmorgan** [comment]
@hsluoyz ahh gotcha. Looking at some of the code it looks like the interfaces read/write to files in the filesystem. Is there a plan to support using adapters? I'm looking at a way to get a ui into the database stored policies in my system.

**Comment by hsluoyz** [comment]
Yeah. We want to support DB. Can you make a PR for it?

**Comment by chmorgan** [comment]
@hsluoyz it might overlap with some work I'm looking at doing. I'm trying to figure out if there is a better approach. Something like using Casbin-server to expose a restful-api and then casbin-ui to consume it like:

Casbin-server <-> casbin-ui

In my case I'll probably build directly against Casbin with my golang application, using Gorm-adapter, and thank you for updating that, but it doesn't make sense for me to add a new api for casbin-ui if I could use Casbin-server to host that.

Thoughts?

**Comment by hsluoyz** [comment]
@chmorgan I think you are correct. We can improve Casbin-UI to make it consume RESTful API of Casbin-Server. Can you help it?

**Comment by chmorgan** [comment]
@hsluoyz I might be aligned to do so in the near future and will be sure to submit some pull requests when I arrive back to my casbin integration work.

**Comment by hsluoyz** [comment]
Thanks !
